<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro/Ace Laravel Export (1.8.1)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateTeleradContractsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('telerad_contracts', function (Blueprint $table) {
            $table->increments('id');
            $table->string('reader_id', 16)->nullable();
            $table->string('reader_gateway_destination', 128)->nullable()->default('');
            $table->string('sender_ns_name', 64)->nullable()->default('');
            $table->string('sender_gateway_destination', 64)->nullable()->default('');
            $table->string('reports_email', 64)->nullable();
            $table->string('specialty', 64)->nullable();
            $table->string('doc_firstname', 32)->nullable();
            $table->string('doc_lastname', 32)->nullable();
            $table->string('doc_middlename', 32)->nullable();
            $table->string('doc_suffix', 16)->nullable();
            $table->string('doc_address1', 64)->nullable();
            $table->char('doc_address2', 65)->nullable();
            $table->string('doc_city', 32)->nullable();
            $table->string('doc_state', 16)->nullable();
            $table->string('doc_country', 16)->nullable();
            $table->string('doc_postal', 16)->nullable();
            $table->string('doc_npi', 16)->nullable();
            $table->string('doc_license_id', 16)->nullable();
            $table->string('doc_license_country', 16)->nullable();
            $table->string('tax_id', 16)->nullable();
            $table->string('ssn', 16)->nullable();
            $table->string('doc_phone_country', 4)->nullable();
            $table->string('doc_phone_number', 16)->nullable();
            $table->string('providertype', 16)->nullable();
            $table->string('dea', 16)->nullable();
            $table->string('taxonomy', 16)->nullable();
            $table->string('notes', 4096)->nullable();
            $table->string('orthanc_server_ids', 64)->default('[]');

            $table->charset = 'utf8mb4';
            $table->collation = 'utf8mb4_unicode_ci';
        });
        
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('telerad_contracts');
    }
}
