<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro/Ace Laravel Export (1.8.1)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateFacilityTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('facility', function (Blueprint $table) {
            $table->increments('id');
            $table->string('name', 64)->nullable();
            $table->string('address_1', 64)->nullable();
            $table->string('address_2', 64)->nullable();
            $table->string('city', 64)->nullable();
            $table->string('state', 64)->nullable();
            $table->string('country', 30)->default('');
            $table->string('country_code_3', 3)->default('');
            $table->string('postal_code', 11)->nullable();
            $table->string('phone_ctry', 30)->nullable();
            $table->string('phone', 30)->nullable();
            $table->string('fax_country', 30)->nullable();
            $table->string('fax', 30)->nullable();
            $table->string('website', 255)->nullable();
            $table->string('email', 255)->nullable();
            $table->string('facilitylogopath', 64)->nullable();
            $table->text('google_maps_url')->nullable();
            $table->string('federal_ein', 15)->nullable();
            $table->tinyInteger('service_location')->default(1);
            $table->tinyInteger('billing_location')->default(0);
            $table->string('facility_currency', 3)->nullable();
            $table->decimal('billing_interest-rate', 3, 2)->nullable();
            $table->tinyInteger('accepts_assignment')->default(0);
            $table->tinyInteger('pos_code')->nullable();
            $table->string('x12_sender_id', 25)->nullable();
            $table->string('attn', 65)->nullable();
            $table->string('domain_identifier', 60)->nullable();
            $table->string('facility_npi', 15)->nullable();
            $table->string('facility_taxonomy', 15)->nullable();
            $table->string('tax_id_type', 31)->default('');
            $table->string('color', 7)->default('');
            $table->integer('primary_business_entity')->default(0)->comment('0-Not Set as business entity 1-Set as business entity');
            $table->string('facility_code', 31)->nullable();
            $table->tinyInteger('extra_validation')->default(1);
            $table->string('mail_street', 30)->nullable();
            $table->string('mail_street2', 30)->nullable();
            $table->string('mail_city', 50)->nullable();
            $table->string('mail_state', 3)->nullable();
            $table->string('mail_country', 3)->nullable();
            $table->string('mail_zip', 10)->nullable();
            $table->string('oid', 255)->default('')->comment('HIEs CCDA and FHIR an OID is required/wanted');
            $table->integer('orthanc_host')->nullable();

            $table->charset = 'utf8mb4';
            $table->collation = 'utf8mb4_unicode_ci';
        });
        
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('facility');
    }
}
