#docker-compose up --build
version: "2"
services:
  nginx:
    image: nginx
    depends_on: [pacs-1,mysql_db]
    restart: unless-stopped
    ports: ["443:443"]
    volumes:
       - ./nginx-home:/nginx-home
       - ./nginx-home/PortalRads/public/storage:/nginx-home/PortalRads/public/storage
       - ./tls:/etc/nginx/tls
       - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  php-fpm:
    build: php-fpm
    volumes:
       - ./nginx-home:/nginx-home
       - ./nginx-home/PortalRads/public/storage:/nginx-home/PortalRads/public/storage
       
       

  pacs-1:
      build: pacs-1
      depends_on: [postgres_index-db]
      restart: unless-stopped
      ports: ["4444:4242"]
      volumes: ["./OrthancStorage:/var/lib/orthanc/db","./MWLFiles:/var/lib/orthanc/worklists","./pacs-1/dicomFiles:/etc/orthanc/dicomFiles", "./pacs-1/python:/python"]
      environment:

          VERBOSE_ENABLED: "false"
          VERBOSE_STARTUP: "true"
          TRACE_ENABLED: "false"
          # AUTHORIZATION_PLUGIN_ENABLED: "false" DEPRECATED, USE OTHER METHOD
          CONNECTIVITY_CHECKS_PLUGIN_ENABLED: "true"
          ORTHANC__AUTHENTICATION_ENABLED: "false"
#         ORTHANC__REGISTERED_USERS: |
#           {"demo": "demo"}
          ORTHANC__NAME: "SCOTTI_CUSTOM"
          ORTHANC__DICOM_SERVER_ENABLED: "true"
          ORTHANC__DICOM_AET: "SCOTTI_CUSTOM"
          # GDCM On by Default
          # GDCM_PLUGIN_ENABLED: "true"
#            {
#            "Gdcm": {
#            "Throttling": 4,
#            "RestrictTransferSyntaxes": [
#              "1.2.840.10008.1.2.4.90",
#              "1.2.840.10008.1.2.4.91",
#              "1.2.840.10008.1.2.4.92",
#              "1.2.840.10008.1.2.4.93"
#            ]
#            }
#            }
          # MWL WORKLISTS -> "/var/lib/orthanc/worklists"
          WORKLISTS_PLUGIN_ENABLED: "true"
          # PYTHON
          ORTHANC__PYTHON_SCRIPT: "/python/combined.py"
          ORTHANC__PYTHON_VERBOSE: "true"
          # OSIMIS VIEWER
          OSIMIS_WEB_VIEWER1_PLUGIN_ENABLED: "true"
          # STONE VIEWER
          # you must enable the StoneViewer and the DicomWeb plugins
          STONE_WEB_VIEWER_PLUGIN_ENABLED: "true"
          DICOM_WEB_PLUGIN_ENABLED: "true"
          ORTHANC__STONE_WEB_VIEWER__DATE_FORMAT: "DD/MM/YYYY"

          # POSTGRES
          ORTHANC__POSTGRESQL__PASSWORD: "postgres"
          ORTHANC__POSTGRESQL__HOST: "postgres_index-db"
          
  #Postgres Service
  postgres_index-db:
  
      image: postgres
      ports: ["5555:5432"]
      restart: unless-stopped
      volumes:
          - ./OrthancIndex:/var/lib/postgresql/data
      environment:
          POSTGRES_PASSWORD: "postgres"
          
          
  #MySQL Service
  mysql_db:
    image: mysql
    command: 
        --default-authentication-plugin=mysql_native_password
        --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

    restart: unless-stopped
    tty: true
    ports: ["3333:3306"]
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'caymanmed'
      MYSQL_PASSWORD: 'caymanmed'
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./MySQL_DB:/var/lib/mysql/
      - ./mysql_init/init.sql:/docker-entrypoint-initdb.d/init.sql
      #- ./mysql/my.cnf:/etc/mysql/my.cnf
      
      
# run that on the host.
#version: "3.1"
#services:
#  mc:
#    image: nextgenhealthcare/connect
#    environment:
#      - DATABASE=postgres
#      - DATABASE_URL=jdbc:postgresql://db:5432/mirthdb
#      - DATABASE_MAX_CONNECTIONS=20
#      - DATABASE_USERNAME=mirthdb
#      - DATABASE_PASSWORD=mirthdb
#      - KEYSTORE_STOREPASS=docker_storepass
#      - KEYSTORE_KEYPASS=docker_keypass
#      - VMOPTIONS=-Xmx512m
#    ports:
#      - 8080:8080/tcp
#      - 8443:8443/tcp
#    depends_on:
#      - db
#  db:
#    image: postgres
#    environment:
#      - POSTGRES_USER=mirthdb
#      - POSTGRES_PASSWORD=mirthdb
#      - POSTGRES_DB=mirthdb
#    expose:
#      - 5432      