<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro/Ace Laravel Export (1.8.1)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateOrdersTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('orders', function (Blueprint $table) {
            $table->increments('id');
            $table->string('priority', 16)->nullable();
            $table->string('accession_number', 16)->nullable();
            $table->string('patientid', 16)->nullable();
            $table->string('ourstatus', 8)->nullable();
            $table->string('requested_procedure_id', 32)->nullable();
            $table->string('coded_exam', 1024)->nullable();
            $table->string('coding_scheme', 16)->nullable();
            $table->string('StudyInstanceUID', 64)->nullable();
            $table->text('message')->nullable();
            $table->string('patient_fname', 64)->nullable();
            $table->string('patient_lname', 64)->nullable();
            $table->string('patient_mname', 64)->nullable();
            $table->string('patient_name', 64)->nullable();
            $table->date('patient_birth_date')->nullable();
            $table->string('patient_sex', 16)->nullable();
            $table->string('referring_physician', 64)->nullable();
            $table->string('referring_physician_id', 16)->nullable();
            $table->string('sending_facility', 64)->nullable();
            $table->string('modality', 16)->nullable();
            $table->string('description', 256)->nullable();
            $table->string('scheduled_station_aetitle', 32)->nullable();
            $table->integer('calendar_id')->nullable();
            $table->date('scheduled_procedure_step_start_date')->nullable();
            $table->time('scheduled_procedure_step_start_time')->nullable();
            $table->string('indication', 256)->nullable();
            $table->integer('exam_length')->nullable();
            $table->dateTime('timestamp')->nullable();
            $table->integer('orderedbyuser_id')->nullable();
            $table->string('orderbyuser_name', 64)->nullable();
            $table->string('related_employment', 4)->nullable();
            $table->string('related_auto', 4)->nullable();
            $table->string('related_otheraccident', 4)->nullable();
            $table->string('related_emergency', 4)->nullable();
            $table->string('related_drugs', 4)->nullable();
            $table->date('related_pregnancy')->nullable();
            $table->string('employed', 4)->nullable();
            $table->string('employed_student', 4)->nullable();
            $table->string('employed_other', 4)->nullable();
            $table->date('illness_date')->nullable();
            $table->string('apptid', 8)->nullable();
            $table->char('priorauth', 16)->nullable();

            $table->charset = 'utf8mb4';
            $table->collation = 'utf8mb4_unicode_ci';
        });
        
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('orders');
    }
}
