<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro/Ace Laravel Export (1.8.1)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateDicomUploadsTempTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('dicom_uploads_temp', function (Blueprint $table) {
            $table->increments('id');
            $table->unsignedInteger('uploader_id')->nullable();
            $table->string('uploader_name', 255)->nullable();
            $table->string('date_time_key', 255)->nullable();
            $table->integer('counter_index')->nullable();
            $table->tinyInteger('aborted_flag')->nullable();
            $table->json('utc_hit_json')->nullable();
            $table->json('study_uuid_json')->nullable();

            $table->charset = 'utf8mb4';
            $table->collation = 'utf8mb4_unicode_ci';
        });
        
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('dicom_uploads_temp');
    }
}
